apiVersion: v1
kind: Service
metadata:
  name: backend-demo-app-service
spec:
  type: NodePort
  selector:
    app: backend-demo-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30005